print("Deekay")
print("\nDeekay" * 4)
print("Dinesh" + " " + "Arul")
name = input("Enter you Name !!!!")
print(f'Hello {name} !')
length = len(name)
print(f'Deekay \'devil\'')
print(length)
print(name[0])
print(name[-2])